version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
      timezone: Europe/Lisbon
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
      timezone: Europe/Lisbon
