#!/usr/bin/env bash

model="qwen2.5-coder:14b"

if [[ $# -gt 1 ]]; then
    model="$1"
    shift
fi

if [[ $# -eq 0 ]]; then
    ollama run --nowordwrap "$model"
else
    ollama run --nowordwrap "$model" "$@"
fi
