[general]
import = ["~/.dotfiles/.config/alacritty/themes/themes/one_dark.toml"]

[font]
size = 12.0

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[window]
option_as_alt = "Both"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "Vi"
